name: Hello
on: 
  workflow_dispatch:
jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello, GitHub Actions!"

  say-bye:
    needs: say-hi
    runs-on: ubuntu-latest
    steps:
      - name: Print second message
        run: echo "This is the second job, running after the first one!"
